CREATE DATABASE IF NOT EXISTS ECOMMERCE_DB;

USE ECOMMERCE_DB;


-- =========================================================
-- USERS AND ACCESS CONTROL
-- =========================================================

CREATE TABLE USERS (
    USER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(20),
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL)
);


CREATE TABLE ROLES (
    ROLE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ROLE_NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255),

    CONSTRAINT UQ_ROLE_NAME UNIQUE (ROLE_NAME)
);


CREATE TABLE USER_ROLES (
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    ASSIGNED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (USER_ID, ROLE_ID),

    CONSTRAINT FK_USER_ROLE_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_USER_ROLE_ROLE
        FOREIGN KEY (ROLE_ID)
        REFERENCES ROLES(ROLE_ID)
        ON DELETE CASCADE
);


CREATE TABLE ADDRESSES (
    ADDRESS_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    ADDRESS_TYPE VARCHAR(20) DEFAULT 'SHIPPING',
    RECIPIENT_NAME VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(20),
    HOUSE_NUMBER VARCHAR(50),
    ADDRESS_LINE_1 VARCHAR(255) NOT NULL,
    ADDRESS_LINE_2 VARCHAR(255),
    CITY VARCHAR(100) NOT NULL,
    STATE VARCHAR(100) NOT NULL,
    PINCODE VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(100) NOT NULL,
    IS_DEFAULT BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_ADDRESS_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE,

    CONSTRAINT CHK_ADDRESS_TYPE
        CHECK (ADDRESS_TYPE IN ('SHIPPING', 'BILLING', 'BOTH'))
);

CREATE INDEX IDX_ADDRESSES_USER_ID
    ON ADDRESSES(USER_ID);


-- =========================================================
-- TAX AND PRODUCT CATALOG
-- =========================================================

CREATE TABLE TAX_RATES (
    TAX_RATE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TAX_NAME VARCHAR(100) NOT NULL,
    COUNTRY VARCHAR(100),
    STATE VARCHAR(100),
    RATE_PERCENT DECIMAL(7, 4) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    VALID_FROM DATETIME,
    VALID_TO DATETIME,

    CONSTRAINT CHK_TAX_RATE
        CHECK (RATE_PERCENT >= 0)
);


CREATE TABLE PRODUCTS (
    PRODUCT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TAX_RATE_ID BIGINT,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    PRODUCT_DESCRIPTION TEXT,
    BRAND VARCHAR(150),
    BASE_PRICE DECIMAL(12, 2) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT FK_PRODUCT_TAX_RATE
        FOREIGN KEY (TAX_RATE_ID)
        REFERENCES TAX_RATES(TAX_RATE_ID)
        ON DELETE SET NULL,

    CONSTRAINT CHK_PRODUCT_PRICE
        CHECK (BASE_PRICE >= 0)
);

CREATE INDEX IDX_PRODUCTS_NAME
    ON PRODUCTS(PRODUCT_NAME);

CREATE INDEX IDX_PRODUCTS_BRAND
    ON PRODUCTS(BRAND);


CREATE TABLE CATEGORIES (
    CATEGORY_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PARENT_CATEGORY_ID BIGINT,
    CATEGORY_NAME VARCHAR(150) NOT NULL,
    DESCRIPTION TEXT,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (CATEGORY_NAME),

    CONSTRAINT FK_CATEGORY_PARENT
        FOREIGN KEY (PARENT_CATEGORY_ID)
        REFERENCES CATEGORIES(CATEGORY_ID)
        ON DELETE SET NULL
);

INSERT INTO CATEGORIES (CATEGORY_NAME, DESCRIPTION, IS_ACTIVE)
VALUES
    ('Men', 'Eyewear designed for men', TRUE),
    ('Women', 'Eyewear designed for women', TRUE),
    ('Unisex', 'Eyewear designed for everyone', TRUE),
    ('Accessory', 'Eyewear accessories and care products', TRUE);


CREATE TABLE PRODUCT_CATEGORIES (
    PRODUCT_ID BIGINT NOT NULL,
    CATEGORY_ID BIGINT NOT NULL,

    PRIMARY KEY (PRODUCT_ID, CATEGORY_ID),

    CONSTRAINT FK_PRODUCT_CATEGORY_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_PRODUCT_CATEGORY_CATEGORY
        FOREIGN KEY (CATEGORY_ID)
        REFERENCES CATEGORIES(CATEGORY_ID)
        ON DELETE CASCADE
);

CREATE INDEX IDX_PRODUCT_CATEGORIES_CATEGORY
    ON PRODUCT_CATEGORIES(CATEGORY_ID);


CREATE TABLE PRODUCT_IMAGES (
    IMAGE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_ID BIGINT NOT NULL,
    IMAGE_URL VARCHAR(2048) NOT NULL,
    ALT_TEXT VARCHAR(255),
    DISPLAY_ORDER INT NOT NULL DEFAULT 0,
    IS_PRIMARY BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT FK_PRODUCT_IMAGE_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID)
        ON DELETE CASCADE,

    CONSTRAINT CHK_IMAGE_DISPLAY_ORDER
        CHECK (DISPLAY_ORDER >= 0)
);

CREATE INDEX IDX_PRODUCT_IMAGES_PRODUCT
    ON PRODUCT_IMAGES(PRODUCT_ID);


CREATE TABLE PRODUCT_VARIANTS (
    VARIANT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_ID BIGINT NOT NULL,
    SKU VARCHAR(100) NOT NULL,
    VARIANT_NAME VARCHAR(255),
    VARIANT_DESCRIPTION TEXT,
    PRICE DECIMAL(12, 2) NOT NULL,
    QUANTITY_AVAILABLE INT NOT NULL DEFAULT 0,
    LOW_STOCK_THRESHOLD INT NOT NULL DEFAULT 5,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT UQ_VARIANT_SKU UNIQUE (SKU),

    CONSTRAINT FK_VARIANT_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID)
        ON DELETE CASCADE,

    CONSTRAINT CHK_VARIANT_PRICE
        CHECK (PRICE >= 0),

    CONSTRAINT CHK_VARIANT_QUANTITY
        CHECK (QUANTITY_AVAILABLE >= 0),

    CONSTRAINT CHK_LOW_STOCK_THRESHOLD
        CHECK (LOW_STOCK_THRESHOLD >= 0)
);

CREATE INDEX IDX_PRODUCT_VARIANTS_PRODUCT
    ON PRODUCT_VARIANTS(PRODUCT_ID);


CREATE TABLE PRODUCT_ATTRIBUTES (
    ATTRIBUTE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_ID BIGINT NOT NULL,
    VARIANT_ID BIGINT,
    ATTRIBUTE_NAME VARCHAR(100) NOT NULL,
    ATTRIBUTE_VALUE VARCHAR(255) NOT NULL,

    CONSTRAINT FK_ATTRIBUTE_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_ATTRIBUTE_VARIANT
        FOREIGN KEY (VARIANT_ID)
        REFERENCES PRODUCT_VARIANTS(VARIANT_ID)
        ON DELETE CASCADE,

    CONSTRAINT UQ_PRODUCT_ATTRIBUTE
        UNIQUE (
            PRODUCT_ID,
            VARIANT_ID,
            ATTRIBUTE_NAME,
            ATTRIBUTE_VALUE
        )
);

CREATE INDEX IDX_PRODUCT_ATTRIBUTES_PRODUCT
    ON PRODUCT_ATTRIBUTES(PRODUCT_ID);

CREATE INDEX IDX_PRODUCT_ATTRIBUTES_VARIANT
    ON PRODUCT_ATTRIBUTES(VARIANT_ID);


CREATE TABLE INVENTORY_MOVEMENTS (
    INVENTORY_MOVEMENT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    VARIANT_ID BIGINT NOT NULL,
    MOVEMENT_TYPE VARCHAR(30) NOT NULL,
    QUANTITY_CHANGE INT NOT NULL,
    REFERENCE_TYPE VARCHAR(50),
    REFERENCE_ID BIGINT,
    NOTES VARCHAR(500),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_INVENTORY_VARIANT
        FOREIGN KEY (VARIANT_ID)
        REFERENCES PRODUCT_VARIANTS(VARIANT_ID),

    CONSTRAINT CHK_INVENTORY_MOVEMENT_TYPE
        CHECK (
            MOVEMENT_TYPE IN (
                'PURCHASE',
                'SALE',
                'CANCELLATION',
                'RETURN',
                'ADJUSTMENT'
            )
        ),

    CONSTRAINT CHK_INVENTORY_CHANGE
        CHECK (QUANTITY_CHANGE <> 0)
);

CREATE INDEX IDX_INVENTORY_VARIANT
    ON INVENTORY_MOVEMENTS(VARIANT_ID);

CREATE INDEX IDX_INVENTORY_REFERENCE
    ON INVENTORY_MOVEMENTS(REFERENCE_TYPE, REFERENCE_ID);


-- =========================================================
-- SHOPPING CARTS AND WISHLISTS
-- =========================================================

CREATE TABLE CARTS (
    CART_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    CART_STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT FK_CART_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE,

    CONSTRAINT CHK_CART_STATUS
        CHECK (CART_STATUS IN ('ACTIVE', 'ORDERED', 'ABANDONED'))
);

CREATE INDEX IDX_CARTS_USER_STATUS
    ON CARTS(USER_ID, CART_STATUS);


CREATE TABLE CART_ITEMS (
    CART_ITEM_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CART_ID BIGINT NOT NULL,
    VARIANT_ID BIGINT NOT NULL,
    QUANTITY INT NOT NULL,
    ADDED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT UQ_CART_VARIANT UNIQUE (CART_ID, VARIANT_ID),

    CONSTRAINT FK_CART_ITEM_CART
        FOREIGN KEY (CART_ID)
        REFERENCES CARTS(CART_ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_CART_ITEM_VARIANT
        FOREIGN KEY (VARIANT_ID)
        REFERENCES PRODUCT_VARIANTS(VARIANT_ID),

    CONSTRAINT CHK_CART_ITEM_QUANTITY
        CHECK (QUANTITY > 0)
);


CREATE TABLE WISHLISTS (
    WISHLIST_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    WISHLIST_NAME VARCHAR(100) NOT NULL DEFAULT 'DEFAULT',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT UQ_USER_WISHLIST
        UNIQUE (USER_ID, WISHLIST_NAME),

    CONSTRAINT FK_WISHLIST_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
);


CREATE TABLE WISHLIST_ITEMS (
    WISHLIST_ITEM_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    WISHLIST_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    ADDED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT UQ_WISHLIST_PRODUCT
        UNIQUE (WISHLIST_ID, PRODUCT_ID),

    CONSTRAINT FK_WISHLIST_ITEM_WISHLIST
        FOREIGN KEY (WISHLIST_ID)
        REFERENCES WISHLISTS(WISHLIST_ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_WISHLIST_ITEM_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID)
        ON DELETE CASCADE
);


-- =========================================================
-- COUPONS
-- =========================================================

CREATE TABLE COUPONS (
    COUPON_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    COUPON_CODE VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255),
    DISCOUNT_TYPE VARCHAR(20) NOT NULL,
    DISCOUNT_VALUE DECIMAL(12, 2) NOT NULL,
    MINIMUM_ORDER_AMOUNT DECIMAL(12, 2) NOT NULL DEFAULT 0,
    MAXIMUM_DISCOUNT_AMOUNT DECIMAL(12, 2),
    USAGE_LIMIT INT,
    USAGE_LIMIT_PER_USER INT,
    VALID_FROM DATETIME NOT NULL,
    VALID_TO DATETIME NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT UQ_COUPON_CODE UNIQUE (COUPON_CODE),

    CONSTRAINT CHK_COUPON_TYPE
        CHECK (DISCOUNT_TYPE IN ('PERCENTAGE', 'FIXED', 'PAIR_FIXED')),

    CONSTRAINT CHK_COUPON_VALUE
        CHECK (DISCOUNT_VALUE > 0),

    CONSTRAINT CHK_COUPON_MINIMUM_AMOUNT
        CHECK (MINIMUM_ORDER_AMOUNT >= 0),

    CONSTRAINT CHK_COUPON_DATES
        CHECK (VALID_TO > VALID_FROM)
);


-- =========================================================
-- ORDERS
-- =========================================================

CREATE TABLE ORDERS (
    ORDER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    SHIPPING_ADDRESS_ID BIGINT,
    BILLING_ADDRESS_ID BIGINT,
    COUPON_ID BIGINT,
    ORDER_STATUS VARCHAR(30) NOT NULL DEFAULT 'PLACED',
    SUBTOTAL_AMOUNT DECIMAL(12, 2) NOT NULL,
    DISCOUNT_AMOUNT DECIMAL(12, 2) NOT NULL DEFAULT 0,
    TAX_AMOUNT DECIMAL(12, 2) NOT NULL DEFAULT 0,
    SHIPPING_AMOUNT DECIMAL(12, 2) NOT NULL DEFAULT 0,
    TOTAL_AMOUNT DECIMAL(12, 2) NOT NULL,

    SHIPPING_NAME VARCHAR(255) NOT NULL,
    SHIPPING_PHONE VARCHAR(20),
    SHIPPING_ADDRESS_LINE_1 VARCHAR(255) NOT NULL,
    SHIPPING_ADDRESS_LINE_2 VARCHAR(255),
    SHIPPING_CITY VARCHAR(100) NOT NULL,
    SHIPPING_STATE VARCHAR(100) NOT NULL,
    SHIPPING_PINCODE VARCHAR(20) NOT NULL,
    SHIPPING_COUNTRY VARCHAR(100) NOT NULL,

    PURCHASED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELIVERED_AT DATETIME,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT FK_ORDER_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT FK_ORDER_SHIPPING_ADDRESS
        FOREIGN KEY (SHIPPING_ADDRESS_ID)
        REFERENCES ADDRESSES(ADDRESS_ID)
        ON DELETE SET NULL,

    CONSTRAINT FK_ORDER_BILLING_ADDRESS
        FOREIGN KEY (BILLING_ADDRESS_ID)
        REFERENCES ADDRESSES(ADDRESS_ID)
        ON DELETE SET NULL,

    CONSTRAINT FK_ORDER_COUPON
        FOREIGN KEY (COUPON_ID)
        REFERENCES COUPONS(COUPON_ID)
        ON DELETE SET NULL,

    CONSTRAINT CHK_ORDER_STATUS
        CHECK (
            ORDER_STATUS IN (
                'PLACED',
                'CONFIRMED',
                'PROCESSING',
                'SHIPPED',
                'DELIVERED',
                'CANCELLED',
                'RETURNED'
            )
        ),

    CONSTRAINT CHK_ORDER_AMOUNTS
        CHECK (
            SUBTOTAL_AMOUNT >= 0
            AND DISCOUNT_AMOUNT >= 0
            AND TAX_AMOUNT >= 0
            AND SHIPPING_AMOUNT >= 0
            AND TOTAL_AMOUNT >= 0
        )
);

CREATE INDEX IDX_ORDERS_USER
    ON ORDERS(USER_ID);

CREATE INDEX IDX_ORDERS_STATUS
    ON ORDERS(ORDER_STATUS);

CREATE INDEX IDX_ORDERS_PURCHASED_AT
    ON ORDERS(PURCHASED_AT);


CREATE TABLE ORDER_ITEMS (
    ORDER_ITEM_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID BIGINT NOT NULL,
    VARIANT_ID BIGINT NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    SKU VARCHAR(100) NOT NULL,
    QUANTITY INT NOT NULL,
    UNIT_PRICE DECIMAL(12, 2) NOT NULL,
    TAX_AMOUNT DECIMAL(12, 2) NOT NULL DEFAULT 0,
    DISCOUNT_AMOUNT DECIMAL(12, 2) NOT NULL DEFAULT 0,
    LINE_TOTAL DECIMAL(12, 2) NOT NULL,

    CONSTRAINT UQ_ORDER_VARIANT
        UNIQUE (ORDER_ID, VARIANT_ID),

    CONSTRAINT FK_ORDER_ITEM_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS(ORDER_ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_ORDER_ITEM_VARIANT
        FOREIGN KEY (VARIANT_ID)
        REFERENCES PRODUCT_VARIANTS(VARIANT_ID),

    CONSTRAINT CHK_ORDER_ITEM_QUANTITY
        CHECK (QUANTITY > 0),

    CONSTRAINT CHK_ORDER_ITEM_AMOUNTS
        CHECK (
            UNIT_PRICE >= 0
            AND TAX_AMOUNT >= 0
            AND DISCOUNT_AMOUNT >= 0
            AND LINE_TOTAL >= 0
        )
);

CREATE INDEX IDX_ORDER_ITEMS_ORDER
    ON ORDER_ITEMS(ORDER_ID);

CREATE INDEX IDX_ORDER_ITEMS_VARIANT
    ON ORDER_ITEMS(VARIANT_ID);


CREATE TABLE ORDER_STATUS_HISTORY (
    ORDER_STATUS_HISTORY_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID BIGINT NOT NULL,
    OLD_STATUS VARCHAR(30),
    NEW_STATUS VARCHAR(30) NOT NULL,
    CHANGED_BY BIGINT,
    NOTES VARCHAR(500),
    CHANGED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_STATUS_HISTORY_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS(ORDER_ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_STATUS_HISTORY_USER
        FOREIGN KEY (CHANGED_BY)
        REFERENCES USERS(USER_ID)
        ON DELETE SET NULL
);

CREATE INDEX IDX_ORDER_STATUS_HISTORY_ORDER
    ON ORDER_STATUS_HISTORY(ORDER_ID);


CREATE TABLE COUPON_USAGE (
    COUPON_USAGE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    COUPON_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    ORDER_ID BIGINT NOT NULL,
    DISCOUNT_AMOUNT DECIMAL(12, 2) NOT NULL,
    USED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT UQ_COUPON_ORDER UNIQUE (COUPON_ID, ORDER_ID),

    CONSTRAINT FK_COUPON_USAGE_COUPON
        FOREIGN KEY (COUPON_ID)
        REFERENCES COUPONS(COUPON_ID),

    CONSTRAINT FK_COUPON_USAGE_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT FK_COUPON_USAGE_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS(ORDER_ID),

    CONSTRAINT CHK_COUPON_USAGE_AMOUNT
        CHECK (DISCOUNT_AMOUNT >= 0)
);

CREATE INDEX IDX_COUPON_USAGE_USER
    ON COUPON_USAGE(USER_ID);


-- =========================================================
-- PAYMENTS AND SHIPMENTS
-- =========================================================

CREATE TABLE PAYMENTS (
    PAYMENT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID BIGINT NOT NULL,
    AMOUNT DECIMAL(12, 2) NOT NULL,
    PAYMENT_METHOD VARCHAR(50) NOT NULL,
    PAYMENT_STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    PAYMENT_PROVIDER VARCHAR(100),
    PROVIDER_REFERENCE VARCHAR(255),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PAID_AT DATETIME,

    CONSTRAINT FK_PAYMENT_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS(ORDER_ID),

    CONSTRAINT CHK_PAYMENT_AMOUNT
        CHECK (AMOUNT > 0),

    CONSTRAINT CHK_PAYMENT_STATUS
        CHECK (
            PAYMENT_STATUS IN (
                'PENDING',
                'AUTHORIZED',
                'PAID',
                'FAILED',
                'CANCELLED',
                'PARTIALLY_REFUNDED',
                'REFUNDED'
            )
        )
);

CREATE INDEX IDX_PAYMENTS_ORDER
    ON PAYMENTS(ORDER_ID);

CREATE INDEX IDX_PAYMENTS_PROVIDER_REFERENCE
    ON PAYMENTS(PROVIDER_REFERENCE);


CREATE TABLE SHIPMENTS (
    SHIPMENT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID BIGINT NOT NULL,
    SHIPPING_PROVIDER VARCHAR(100),
    TRACKING_NUMBER VARCHAR(255),
    SHIPMENT_STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    SHIPPED_AT DATETIME,
    EXPECTED_DELIVERY_AT DATETIME,
    DELIVERED_AT DATETIME,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_SHIPMENT_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS(ORDER_ID),

    CONSTRAINT CHK_SHIPMENT_STATUS
        CHECK (
            SHIPMENT_STATUS IN (
                'PENDING',
                'PACKED',
                'SHIPPED',
                'IN_TRANSIT',
                'OUT_FOR_DELIVERY',
                'DELIVERED',
                'FAILED',
                'RETURNED'
            )
        )
);

CREATE INDEX IDX_SHIPMENTS_ORDER
    ON SHIPMENTS(ORDER_ID);

CREATE INDEX IDX_SHIPMENTS_TRACKING
    ON SHIPMENTS(TRACKING_NUMBER);


-- =========================================================
-- REVIEWS
-- =========================================================

CREATE TABLE REVIEWS (
    REVIEW_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    ORDER_ITEM_ID BIGINT,
    RATING INT NOT NULL,
    REVIEW_TEXT TEXT,
    REVIEW_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT UQ_USER_ORDER_ITEM_REVIEW
        UNIQUE (USER_ID, ORDER_ITEM_ID),

    CONSTRAINT FK_REVIEW_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_REVIEW_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_REVIEW_ORDER_ITEM
        FOREIGN KEY (ORDER_ITEM_ID)
        REFERENCES ORDER_ITEMS(ORDER_ITEM_ID)
        ON DELETE SET NULL,

    CONSTRAINT CHK_REVIEW_RATING
        CHECK (RATING BETWEEN 1 AND 5),

    CONSTRAINT CHK_REVIEW_STATUS
        CHECK (
            REVIEW_STATUS IN (
                'PUBLISHED',
                'PENDING',
                'APPROVED',
                'REJECTED'
            )
        )
);

CREATE INDEX IDX_REVIEWS_PRODUCT_STATUS
    ON REVIEWS(PRODUCT_ID, REVIEW_STATUS);


-- =========================================================
-- RETURNS AND REFUNDS
-- =========================================================

CREATE TABLE RETURNS (
    RETURN_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    RETURN_STATUS VARCHAR(30) NOT NULL DEFAULT 'REQUESTED',
    RETURN_REASON VARCHAR(255) NOT NULL,
    CUSTOMER_COMMENTS TEXT,
    ADMIN_COMMENTS TEXT,
    REQUESTED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    APPROVED_AT DATETIME,
    RECEIVED_AT DATETIME,
    COMPLETED_AT DATETIME,

    CONSTRAINT FK_RETURN_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS(ORDER_ID),

    CONSTRAINT FK_RETURN_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT CHK_RETURN_STATUS
        CHECK (
            RETURN_STATUS IN (
                'REQUESTED',
                'APPROVED',
                'REJECTED',
                'PICKED_UP',
                'RECEIVED',
                'COMPLETED',
                'CANCELLED'
            )
        )
);

CREATE INDEX IDX_RETURNS_ORDER
    ON RETURNS(ORDER_ID);

CREATE INDEX IDX_RETURNS_USER
    ON RETURNS(USER_ID);


CREATE TABLE RETURN_ITEMS (
    RETURN_ITEM_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    RETURN_ID BIGINT NOT NULL,
    ORDER_ITEM_ID BIGINT NOT NULL,
    QUANTITY INT NOT NULL,
    ITEM_CONDITION VARCHAR(50),
    RETURN_REASON VARCHAR(255),

    CONSTRAINT UQ_RETURN_ORDER_ITEM
        UNIQUE (RETURN_ID, ORDER_ITEM_ID),

    CONSTRAINT FK_RETURN_ITEM_RETURN
        FOREIGN KEY (RETURN_ID)
        REFERENCES RETURNS(RETURN_ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_RETURN_ITEM_ORDER_ITEM
        FOREIGN KEY (ORDER_ITEM_ID)
        REFERENCES ORDER_ITEMS(ORDER_ITEM_ID),

    CONSTRAINT CHK_RETURN_ITEM_QUANTITY
        CHECK (QUANTITY > 0)
);


CREATE TABLE REFUNDS (
    REFUND_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PAYMENT_ID BIGINT NOT NULL,
    RETURN_ID BIGINT,
    REFUND_AMOUNT DECIMAL(12, 2) NOT NULL,
    REFUND_STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    PROVIDER_REFERENCE VARCHAR(255),
    REASON VARCHAR(255),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PROCESSED_AT DATETIME,

    CONSTRAINT FK_REFUND_PAYMENT
        FOREIGN KEY (PAYMENT_ID)
        REFERENCES PAYMENTS(PAYMENT_ID),

    CONSTRAINT FK_REFUND_RETURN
        FOREIGN KEY (RETURN_ID)
        REFERENCES RETURNS(RETURN_ID)
        ON DELETE SET NULL,

    CONSTRAINT CHK_REFUND_AMOUNT
        CHECK (REFUND_AMOUNT > 0),

    CONSTRAINT CHK_REFUND_STATUS
        CHECK (
            REFUND_STATUS IN (
                'PENDING',
                'PROCESSING',
                'COMPLETED',
                'FAILED',
                'CANCELLED'
            )
        )
);

CREATE INDEX IDX_REFUNDS_PAYMENT
    ON REFUNDS(PAYMENT_ID);


-- =========================================================
-- CONFIGURATION, NOTIFICATIONS AND AUDITING
-- =========================================================

CREATE TABLE CONFIG (
    CONFIG_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CONFIG_SHORT_CODE VARCHAR(100) NOT NULL,
    CONFIG_VALUE TEXT,
    DESCRIPTION VARCHAR(255),
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT UQ_CONFIG_SHORT_CODE
        UNIQUE (CONFIG_SHORT_CODE)
);


CREATE TABLE NOTIFICATIONS (
    NOTIFICATION_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    NOTIFICATION_TYPE VARCHAR(30) NOT NULL,
    SUBJECT VARCHAR(255),
    MESSAGE TEXT NOT NULL,
    NOTIFICATION_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    SENT_AT DATETIME,
    READ_AT DATETIME,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_NOTIFICATION_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE,

    CONSTRAINT CHK_NOTIFICATION_TYPE
        CHECK (
            NOTIFICATION_TYPE IN (
                'EMAIL',
                'SMS',
                'PUSH',
                'IN_APP'
            )
        ),

    CONSTRAINT CHK_NOTIFICATION_STATUS
        CHECK (
            NOTIFICATION_STATUS IN (
                'PENDING',
                'SENT',
                'FAILED',
                'READ'
            )
        )
);

CREATE INDEX IDX_NOTIFICATIONS_USER_STATUS
    ON NOTIFICATIONS(USER_ID, NOTIFICATION_STATUS);


CREATE TABLE AUDIT_LOGS (
    AUDIT_LOG_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT,
    ACTION_TYPE VARCHAR(100) NOT NULL,
    ENTITY_TYPE VARCHAR(100) NOT NULL,
    ENTITY_ID BIGINT,
    OLD_VALUE JSON,
    NEW_VALUE JSON,
    IP_ADDRESS VARCHAR(45),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_AUDIT_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
        ON DELETE SET NULL
);

CREATE INDEX IDX_AUDIT_ENTITY
    ON AUDIT_LOGS(ENTITY_TYPE, ENTITY_ID);

CREATE INDEX IDX_AUDIT_USER
    ON AUDIT_LOGS(USER_ID);

CREATE INDEX IDX_AUDIT_CREATED_AT
    ON AUDIT_LOGS(CREATED_AT);
    
-- =========================================================
-- SPRING SECURITY
-- =========================================================

CREATE TABLE PERMISSIONS (
    PERMISSION_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PERMISSION_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255),

    CONSTRAINT UQ_PERMISSION_NAME
        UNIQUE (PERMISSION_NAME)
);


CREATE TABLE ROLE_PERMISSIONS (
    ROLE_ID BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,

    PRIMARY KEY (ROLE_ID, PERMISSION_ID),

    CONSTRAINT FK_ROLE_PERMISSION_ROLE
        FOREIGN KEY (ROLE_ID)
        REFERENCES ROLES(ROLE_ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_ROLE_PERMISSION_PERMISSION
        FOREIGN KEY (PERMISSION_ID)
        REFERENCES PERMISSIONS(PERMISSION_ID)
        ON DELETE CASCADE
);


CREATE TABLE REFRESH_TOKENS (
    REFRESH_TOKEN_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    TOKEN_HASH VARCHAR(255) NOT NULL,
    EXPIRES_AT DATETIME NOT NULL,
    REVOKED_AT DATETIME,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY_IP VARCHAR(45),
    REPLACED_BY_TOKEN_HASH VARCHAR(255),

    CONSTRAINT UQ_REFRESH_TOKEN_HASH
        UNIQUE (TOKEN_HASH),

    CONSTRAINT FK_REFRESH_TOKEN_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
);

CREATE INDEX IDX_REFRESH_TOKEN_USER
    ON REFRESH_TOKENS(USER_ID);

CREATE INDEX IDX_REFRESH_TOKEN_EXPIRY
    ON REFRESH_TOKENS(EXPIRES_AT);


CREATE TABLE LOGIN_ATTEMPTS (
    LOGIN_ATTEMPT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(255) NOT NULL,
    IP_ADDRESS VARCHAR(45),
    IS_SUCCESSFUL BOOLEAN NOT NULL,
    FAILURE_REASON VARCHAR(255),
    ATTEMPTED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_LOGIN_ATTEMPTS_EMAIL_TIME
    ON LOGIN_ATTEMPTS(EMAIL, ATTEMPTED_AT);


CREATE TABLE PASSWORD_RESET_TOKENS (
    PASSWORD_RESET_TOKEN_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    TOKEN_HASH VARCHAR(255) NOT NULL,
    EXPIRES_AT DATETIME NOT NULL,
    USED_AT DATETIME,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT UQ_PASSWORD_RESET_TOKEN
        UNIQUE (TOKEN_HASH),

    CONSTRAINT FK_PASSWORD_RESET_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
);


CREATE TABLE EMAIL_VERIFICATION_TOKENS (
    EMAIL_VERIFICATION_TOKEN_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    TOKEN_HASH VARCHAR(255) NOT NULL,
    EXPIRES_AT DATETIME NOT NULL,
    VERIFIED_AT DATETIME,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT UQ_EMAIL_VERIFICATION_TOKEN
        UNIQUE (TOKEN_HASH),

    CONSTRAINT FK_EMAIL_VERIFICATION_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
);


CREATE TABLE EMAIL_OUTBOX (
    EMAIL_OUTBOX_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    RECIPIENT VARCHAR(255) NOT NULL,
    SUBJECT VARCHAR(255) NOT NULL,
    BODY TEXT NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    ATTEMPT_COUNT INT NOT NULL DEFAULT 0,
    NEXT_ATTEMPT_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_ERROR VARCHAR(1000),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    SENT_AT DATETIME,
    EXPIRES_AT DATETIME,
    INDEX IDX_EMAIL_OUTBOX_DUE (STATUS, NEXT_ATTEMPT_AT, CREATED_AT),
    CONSTRAINT CHK_EMAIL_OUTBOX_STATUS
        CHECK (STATUS IN ('PENDING', 'RETRY', 'SENT', 'FAILED')),
    CONSTRAINT CHK_EMAIL_OUTBOX_ATTEMPTS CHECK (ATTEMPT_COUNT >= 0)
) ENGINE=InnoDB;
ALTER TABLE USERS
    ADD COLUMN EMAIL_VERIFIED BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN ACCOUNT_LOCKED BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN FAILED_LOGIN_ATTEMPTS INT NOT NULL DEFAULT 0,
    ADD COLUMN LOCKED_UNTIL DATETIME,
    ADD COLUMN PASSWORD_CHANGED_AT DATETIME,
    ADD COLUMN LAST_LOGIN_AT DATETIME;
sys_configINSERT INTO ROLES (ROLE_NAME, DESCRIPTION)
VALUES
    ('CUSTOMER', 'Regular e-commerce customer'),
    ('ADMIN', 'Full system administrator'),
    ('SUPPORT', 'Customer support employee'),
    ('INVENTORY_MANAGER', 'Manages products and inventory');


INSERT INTO PERMISSIONS (PERMISSION_NAME, DESCRIPTION)
VALUES
    ('PRODUCT_READ', 'View products'),
    ('PRODUCT_WRITE', 'Create and update products'),
    ('PRODUCT_DELETE', 'Delete products'),
    ('ORDER_CREATE', 'Place an order'),
    ('ORDER_READ_OWN', 'View own orders'),
    ('ORDER_READ_ALL', 'View every order'),
    ('ORDER_UPDATE', 'Update order status'),
    ('USER_READ', 'View user details'),
    ('USER_UPDATE', 'Update user details'),
    ('RETURN_CREATE', 'Request a return'),
    ('RETURN_MANAGE', 'Approve or reject returns'),
    ('INVENTORY_MANAGE', 'Manage inventory');


INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID
FROM ROLES R
JOIN PERMISSIONS P
WHERE R.ROLE_NAME = 'CUSTOMER'
  AND P.PERMISSION_NAME IN (
      'PRODUCT_READ',
      'ORDER_CREATE',
      'ORDER_READ_OWN',
      'USER_UPDATE',
      'RETURN_CREATE'
  );


INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID
FROM ROLES R
CROSS JOIN PERMISSIONS P
WHERE R.ROLE_NAME = 'ADMIN';


INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID
FROM ROLES R
JOIN PERMISSIONS P
WHERE R.ROLE_NAME = 'SUPPORT'
  AND P.PERMISSION_NAME IN (
      'PRODUCT_READ',
      'ORDER_READ_ALL',
      'ORDER_UPDATE',
      'USER_READ',
      'RETURN_MANAGE'
  );


INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID
FROM ROLES R
JOIN PERMISSIONS P
WHERE R.ROLE_NAME = 'INVENTORY_MANAGER'
  AND P.PERMISSION_NAME IN (
      'PRODUCT_READ',
      'PRODUCT_WRITE',
      'INVENTORY_MANAGE'
  );
  
  
  select * from PRODUCTS;
  
  select * from users;
  
  select * from PRODUCTS;
  select * from user_roles;
  
  
  INSERT IGNORE INTO user_roles (USER_ID, ROLE_ID)
SELECT u.USER_ID, r.ROLE_ID
FROM USERS u
JOIN ROLES r ON r.ROLE_NAME = 'ADMIN'
WHERE u.EMAIL = 'admin@example.com';
