-- Add Shiprocket integration columns to SHIPMENTS table.
-- Run against the production database BEFORE deploying the new code.

ALTER TABLE SHIPMENTS
    ADD COLUMN SHIPROCKET_ORDER_ID    BIGINT       NULL AFTER TRACKING_NUMBER,
    ADD COLUMN SHIPROCKET_SHIPMENT_ID BIGINT       NULL AFTER SHIPROCKET_ORDER_ID,
    ADD COLUMN AWB_CODE               VARCHAR(100) NULL AFTER SHIPROCKET_SHIPMENT_ID,
    ADD COLUMN COURIER_NAME           VARCHAR(100) NULL AFTER AWB_CODE,
    ADD COLUMN LABEL_URL              VARCHAR(1000) NULL AFTER COURIER_NAME;

-- Index on AWB_CODE for webhook lookups (Shiprocket sends the AWB in tracking updates).
CREATE INDEX IDX_SHIPMENTS_AWB_CODE ON SHIPMENTS (AWB_CODE);

-- Index on SHIPROCKET_ORDER_ID for order-level lookups.
CREATE INDEX IDX_SHIPMENTS_SHIPROCKET_ORDER_ID ON SHIPMENTS (SHIPROCKET_ORDER_ID);
