-- Durable transactional email queue. Safe to execute repeatedly.
CREATE TABLE IF NOT EXISTS EMAIL_OUTBOX (
    EMAIL_OUTBOX_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    RECIPIENT VARCHAR(255) NOT NULL,
    SUBJECT VARCHAR(255) NOT NULL,
    BODY TEXT NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    ATTEMPT_COUNT INT NOT NULL DEFAULT 0,
    NEXT_ATTEMPT_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_ERROR VARCHAR(1000),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    SENT_AT DATETIME,
    EXPIRES_AT DATETIME,
    INDEX IDX_EMAIL_OUTBOX_DUE (STATUS, NEXT_ATTEMPT_AT, CREATED_AT),
    CONSTRAINT CHK_EMAIL_OUTBOX_STATUS
        CHECK (STATUS IN ('PENDING', 'RETRY', 'SENT', 'FAILED')),
    CONSTRAINT CHK_EMAIL_OUTBOX_ATTEMPTS CHECK (ATTEMPT_COUNT >= 0)
) ENGINE=InnoDB;
