-- Upgrade databases where EMAIL_OUTBOX was created before expiry support.
SET @HAS_EXPIRES_AT = (
    SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'EMAIL_OUTBOX'
      AND COLUMN_NAME = 'EXPIRES_AT'
);
SET @ADD_EXPIRES_AT = IF(
    @HAS_EXPIRES_AT = 0,
    'ALTER TABLE EMAIL_OUTBOX ADD COLUMN EXPIRES_AT DATETIME NULL AFTER SENT_AT',
    'SELECT 1'
);
PREPARE EMAIL_OUTBOX_EXPIRY_STMT FROM @ADD_EXPIRES_AT;
EXECUTE EMAIL_OUTBOX_EXPIRY_STMT;
DEALLOCATE PREPARE EMAIL_OUTBOX_EXPIRY_STMT;
