CREATE TABLE IF NOT EXISTS CUSTOMER_COMMUNICATION_PREFERENCES (
    USER_ID BIGINT PRIMARY KEY,
    EMAIL_ORDER_UPDATES BOOLEAN NOT NULL DEFAULT TRUE,
    EMAIL_SHIPMENT_UPDATES BOOLEAN NOT NULL DEFAULT TRUE,
    EMAIL_RETURN_REFUND_UPDATES BOOLEAN NOT NULL DEFAULT TRUE,
    IN_APP_ORDER_UPDATES BOOLEAN NOT NULL DEFAULT TRUE,
    IN_APP_SHIPMENT_UPDATES BOOLEAN NOT NULL DEFAULT TRUE,
    IN_APP_RETURN_REFUND_UPDATES BOOLEAN NOT NULL DEFAULT TRUE,
    IN_APP_REVIEW_UPDATES BOOLEAN NOT NULL DEFAULT TRUE,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_COMMUNICATION_PREFERENCES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB;
