-- Shades World complete MySQL DDL
-- Generated from the current ECOMMERCE_DB structure on 2026-08-06.
-- Intended for a fresh/rebuild installation: this script contains DROP TABLE statements.

CREATE DATABASE IF NOT EXISTS ECOMMERCE_DB CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE ECOMMERCE_DB;

/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `addresses`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `addresses` (
  `ADDRESS_ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint NOT NULL,
  `ADDRESS_TYPE` varchar(20) DEFAULT 'SHIPPING',
  `RECIPIENT_NAME` varchar(255) NOT NULL,
  `PHONE_NUMBER` varchar(20) DEFAULT NULL,
  `HOUSE_NUMBER` varchar(50) DEFAULT NULL,
  `ADDRESS_LINE_1` varchar(255) NOT NULL,
  `ADDRESS_LINE_2` varchar(255) DEFAULT NULL,
  `CITY` varchar(100) NOT NULL,
  `STATE` varchar(100) NOT NULL,
  `PINCODE` varchar(20) NOT NULL,
  `COUNTRY` varchar(100) NOT NULL,
  `IS_DEFAULT` tinyint(1) NOT NULL DEFAULT '0',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ADDRESS_ID`),
  KEY `IDX_ADDRESSES_USER_ID` (`USER_ID`),
  CONSTRAINT `FK_ADDRESS_USER` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`) ON DELETE CASCADE,
  CONSTRAINT `CHK_ADDRESS_TYPE` CHECK ((`ADDRESS_TYPE` in (_utf8mb4'SHIPPING',_utf8mb4'BILLING',_utf8mb4'BOTH')))
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `audit_logs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `audit_logs` (
  `AUDIT_LOG_ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint DEFAULT NULL,
  `ACTION_TYPE` varchar(100) NOT NULL,
  `ENTITY_TYPE` varchar(100) NOT NULL,
  `ENTITY_ID` bigint DEFAULT NULL,
  `OLD_VALUE` json DEFAULT NULL,
  `NEW_VALUE` json DEFAULT NULL,
  `IP_ADDRESS` varchar(45) DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`AUDIT_LOG_ID`),
  KEY `IDX_AUDIT_ENTITY` (`ENTITY_TYPE`,`ENTITY_ID`),
  KEY `IDX_AUDIT_USER` (`USER_ID`),
  KEY `IDX_AUDIT_CREATED_AT` (`CREATED_AT`),
  CONSTRAINT `FK_AUDIT_USER` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `cart_items`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `cart_items` (
  `CART_ITEM_ID` bigint NOT NULL AUTO_INCREMENT,
  `CART_ID` bigint NOT NULL,
  `VARIANT_ID` bigint NOT NULL,
  `QUANTITY` int NOT NULL,
  `ADDED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CART_ITEM_ID`),
  UNIQUE KEY `UQ_CART_VARIANT` (`CART_ID`,`VARIANT_ID`),
  KEY `FK_CART_ITEM_VARIANT` (`VARIANT_ID`),
  CONSTRAINT `FK_CART_ITEM_CART` FOREIGN KEY (`CART_ID`) REFERENCES `carts` (`CART_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_CART_ITEM_VARIANT` FOREIGN KEY (`VARIANT_ID`) REFERENCES `product_variants` (`VARIANT_ID`),
  CONSTRAINT `CHK_CART_ITEM_QUANTITY` CHECK ((`QUANTITY` > 0))
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `carts`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `carts` (
  `CART_ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint NOT NULL,
  `CART_STATUS` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CART_ID`),
  KEY `IDX_CARTS_USER_STATUS` (`USER_ID`,`CART_STATUS`),
  CONSTRAINT `FK_CART_USER` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`) ON DELETE CASCADE,
  CONSTRAINT `CHK_CART_STATUS` CHECK ((`CART_STATUS` in (_utf8mb4'ACTIVE',_utf8mb4'ORDERED',_utf8mb4'ABANDONED')))
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `categories`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `categories` (
  `CATEGORY_ID` bigint NOT NULL AUTO_INCREMENT,
  `PARENT_CATEGORY_ID` bigint DEFAULT NULL,
  `CATEGORY_NAME` varchar(150) NOT NULL,
  `DESCRIPTION` text,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CATEGORY_ID`),
  UNIQUE KEY `UQ_CATEGORY_NAME` (`CATEGORY_NAME`),
  KEY `FK_CATEGORY_PARENT` (`PARENT_CATEGORY_ID`),
  CONSTRAINT `FK_CATEGORY_PARENT` FOREIGN KEY (`PARENT_CATEGORY_ID`) REFERENCES `categories` (`CATEGORY_ID`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `config`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `config` (
  `CONFIG_ID` bigint NOT NULL AUTO_INCREMENT,
  `CONFIG_SHORT_CODE` varchar(100) NOT NULL,
  `CONFIG_VALUE` text,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CONFIG_ID`),
  UNIQUE KEY `UQ_CONFIG_SHORT_CODE` (`CONFIG_SHORT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `coupon_usage`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `coupon_usage` (
  `COUPON_USAGE_ID` bigint NOT NULL AUTO_INCREMENT,
  `COUPON_ID` bigint NOT NULL,
  `USER_ID` bigint NOT NULL,
  `ORDER_ID` bigint NOT NULL,
  `DISCOUNT_AMOUNT` decimal(12,2) NOT NULL,
  `USED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`COUPON_USAGE_ID`),
  UNIQUE KEY `UQ_COUPON_ORDER` (`COUPON_ID`,`ORDER_ID`),
  KEY `FK_COUPON_USAGE_ORDER` (`ORDER_ID`),
  KEY `IDX_COUPON_USAGE_USER` (`USER_ID`),
  CONSTRAINT `FK_COUPON_USAGE_COUPON` FOREIGN KEY (`COUPON_ID`) REFERENCES `coupons` (`COUPON_ID`),
  CONSTRAINT `FK_COUPON_USAGE_ORDER` FOREIGN KEY (`ORDER_ID`) REFERENCES `orders` (`ORDER_ID`),
  CONSTRAINT `FK_COUPON_USAGE_USER` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`),
  CONSTRAINT `CHK_COUPON_USAGE_AMOUNT` CHECK ((`DISCOUNT_AMOUNT` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `coupons`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `coupons` (
  `COUPON_ID` bigint NOT NULL AUTO_INCREMENT,
  `COUPON_CODE` varchar(50) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `DISCOUNT_TYPE` varchar(20) NOT NULL,
  `DISCOUNT_VALUE` decimal(12,2) NOT NULL,
  `MINIMUM_ORDER_AMOUNT` decimal(12,2) NOT NULL DEFAULT '0.00',
  `MAXIMUM_DISCOUNT_AMOUNT` decimal(12,2) DEFAULT NULL,
  `USAGE_LIMIT` int DEFAULT NULL,
  `USAGE_LIMIT_PER_USER` int DEFAULT NULL,
  `VALID_FROM` datetime NOT NULL,
  `VALID_TO` datetime NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`COUPON_ID`),
  UNIQUE KEY `UQ_COUPON_CODE` (`COUPON_CODE`),
  CONSTRAINT `CHK_COUPON_DATES` CHECK ((`VALID_TO` > `VALID_FROM`)),
  CONSTRAINT `CHK_COUPON_MINIMUM_AMOUNT` CHECK ((`MINIMUM_ORDER_AMOUNT` >= 0)),
  CONSTRAINT `CHK_COUPON_TYPE` CHECK ((`DISCOUNT_TYPE` in (_cp850'PERCENTAGE',_cp850'FIXED',_cp850'PAIR_FIXED'))),
  CONSTRAINT `CHK_COUPON_VALUE` CHECK ((`DISCOUNT_VALUE` > 0))
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `customer_communication_preferences`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `customer_communication_preferences` (
  `USER_ID` bigint NOT NULL,
  `EMAIL_ORDER_UPDATES` tinyint(1) NOT NULL DEFAULT '1',
  `EMAIL_SHIPMENT_UPDATES` tinyint(1) NOT NULL DEFAULT '1',
  `EMAIL_RETURN_REFUND_UPDATES` tinyint(1) NOT NULL DEFAULT '1',
  `IN_APP_ORDER_UPDATES` tinyint(1) NOT NULL DEFAULT '1',
  `IN_APP_SHIPMENT_UPDATES` tinyint(1) NOT NULL DEFAULT '1',
  `IN_APP_RETURN_REFUND_UPDATES` tinyint(1) NOT NULL DEFAULT '1',
  `IN_APP_REVIEW_UPDATES` tinyint(1) NOT NULL DEFAULT '1',
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`USER_ID`),
  CONSTRAINT `FK_COMMUNICATION_PREFERENCES_USER` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `email_outbox`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `email_outbox` (
  `EMAIL_OUTBOX_ID` bigint NOT NULL AUTO_INCREMENT,
  `RECIPIENT` varchar(255) NOT NULL,
  `SUBJECT` varchar(255) NOT NULL,
  `BODY` text NOT NULL,
  `STATUS` varchar(20) NOT NULL DEFAULT 'PENDING',
  `ATTEMPT_COUNT` int NOT NULL DEFAULT '0',
  `NEXT_ATTEMPT_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LAST_ERROR` varchar(1000) DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `SENT_AT` datetime DEFAULT NULL,
  `EXPIRES_AT` datetime DEFAULT NULL,
  PRIMARY KEY (`EMAIL_OUTBOX_ID`),
  KEY `IDX_EMAIL_OUTBOX_DUE` (`STATUS`,`NEXT_ATTEMPT_AT`,`CREATED_AT`),
  CONSTRAINT `CHK_EMAIL_OUTBOX_ATTEMPTS` CHECK ((`ATTEMPT_COUNT` >= 0)),
  CONSTRAINT `CHK_EMAIL_OUTBOX_STATUS` CHECK ((`STATUS` in (_utf8mb4'PENDING',_utf8mb4'RETRY',_utf8mb4'SENT',_utf8mb4'FAILED')))
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `email_verification_tokens`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `email_verification_tokens` (
  `EMAIL_VERIFICATION_TOKEN_ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint NOT NULL,
  `TOKEN_HASH` varchar(255) NOT NULL,
  `EXPIRES_AT` datetime NOT NULL,
  `VERIFIED_AT` datetime DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`EMAIL_VERIFICATION_TOKEN_ID`),
  UNIQUE KEY `UQ_EMAIL_VERIFICATION_TOKEN` (`TOKEN_HASH`),
  KEY `FK_EMAIL_VERIFICATION_USER` (`USER_ID`),
  CONSTRAINT `FK_EMAIL_VERIFICATION_USER` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `inventory_movements`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `inventory_movements` (
  `INVENTORY_MOVEMENT_ID` bigint NOT NULL AUTO_INCREMENT,
  `VARIANT_ID` bigint NOT NULL,
  `MOVEMENT_TYPE` varchar(30) NOT NULL,
  `QUANTITY_CHANGE` int NOT NULL,
  `REFERENCE_TYPE` varchar(50) DEFAULT NULL,
  `REFERENCE_ID` bigint DEFAULT NULL,
  `NOTES` varchar(500) DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`INVENTORY_MOVEMENT_ID`),
  KEY `IDX_INVENTORY_VARIANT` (`VARIANT_ID`),
  KEY `IDX_INVENTORY_REFERENCE` (`REFERENCE_TYPE`,`REFERENCE_ID`),
  CONSTRAINT `FK_INVENTORY_VARIANT` FOREIGN KEY (`VARIANT_ID`) REFERENCES `product_variants` (`VARIANT_ID`),
  CONSTRAINT `CHK_INVENTORY_CHANGE` CHECK ((`QUANTITY_CHANGE` <> 0)),
  CONSTRAINT `CHK_INVENTORY_MOVEMENT_TYPE` CHECK ((`MOVEMENT_TYPE` in (_utf8mb4'PURCHASE',_utf8mb4'SALE',_utf8mb4'CANCELLATION',_utf8mb4'RETURN',_utf8mb4'ADJUSTMENT')))
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `login_attempts`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `login_attempts` (
  `LOGIN_ATTEMPT_ID` bigint NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(255) NOT NULL,
  `IP_ADDRESS` varchar(45) DEFAULT NULL,
  `IS_SUCCESSFUL` tinyint(1) NOT NULL,
  `FAILURE_REASON` varchar(255) DEFAULT NULL,
  `ATTEMPTED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`LOGIN_ATTEMPT_ID`),
  KEY `IDX_LOGIN_ATTEMPTS_EMAIL_TIME` (`EMAIL`,`ATTEMPTED_AT`)
) ENGINE=InnoDB AUTO_INCREMENT=50 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `notifications`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `notifications` (
  `NOTIFICATION_ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint NOT NULL,
  `NOTIFICATION_TYPE` varchar(30) NOT NULL,
  `SUBJECT` varchar(255) DEFAULT NULL,
  `MESSAGE` text NOT NULL,
  `NOTIFICATION_STATUS` varchar(20) NOT NULL DEFAULT 'PENDING',
  `SENT_AT` datetime DEFAULT NULL,
  `READ_AT` datetime DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`NOTIFICATION_ID`),
  KEY `IDX_NOTIFICATIONS_USER_STATUS` (`USER_ID`,`NOTIFICATION_STATUS`),
  CONSTRAINT `FK_NOTIFICATION_USER` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`) ON DELETE CASCADE,
  CONSTRAINT `CHK_NOTIFICATION_STATUS` CHECK ((`NOTIFICATION_STATUS` in (_utf8mb4'PENDING',_utf8mb4'SENT',_utf8mb4'FAILED',_utf8mb4'READ'))),
  CONSTRAINT `CHK_NOTIFICATION_TYPE` CHECK ((`NOTIFICATION_TYPE` in (_utf8mb4'EMAIL',_utf8mb4'SMS',_utf8mb4'PUSH',_utf8mb4'IN_APP')))
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `order_items`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `order_items` (
  `ORDER_ITEM_ID` bigint NOT NULL AUTO_INCREMENT,
  `ORDER_ID` bigint NOT NULL,
  `VARIANT_ID` bigint NOT NULL,
  `PRODUCT_NAME` varchar(255) NOT NULL,
  `SKU` varchar(100) NOT NULL,
  `QUANTITY` int NOT NULL,
  `UNIT_PRICE` decimal(12,2) NOT NULL,
  `TAX_AMOUNT` decimal(12,2) NOT NULL DEFAULT '0.00',
  `DISCOUNT_AMOUNT` decimal(12,2) NOT NULL DEFAULT '0.00',
  `LINE_TOTAL` decimal(12,2) NOT NULL,
  PRIMARY KEY (`ORDER_ITEM_ID`),
  UNIQUE KEY `UQ_ORDER_VARIANT` (`ORDER_ID`,`VARIANT_ID`),
  KEY `IDX_ORDER_ITEMS_ORDER` (`ORDER_ID`),
  KEY `IDX_ORDER_ITEMS_VARIANT` (`VARIANT_ID`),
  CONSTRAINT `FK_ORDER_ITEM_ORDER` FOREIGN KEY (`ORDER_ID`) REFERENCES `orders` (`ORDER_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_ORDER_ITEM_VARIANT` FOREIGN KEY (`VARIANT_ID`) REFERENCES `product_variants` (`VARIANT_ID`),
  CONSTRAINT `CHK_ORDER_ITEM_AMOUNTS` CHECK (((`UNIT_PRICE` >= 0) and (`TAX_AMOUNT` >= 0) and (`DISCOUNT_AMOUNT` >= 0) and (`LINE_TOTAL` >= 0))),
  CONSTRAINT `CHK_ORDER_ITEM_QUANTITY` CHECK ((`QUANTITY` > 0))
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `order_status_history`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `order_status_history` (
  `ORDER_STATUS_HISTORY_ID` bigint NOT NULL AUTO_INCREMENT,
  `ORDER_ID` bigint NOT NULL,
  `OLD_STATUS` varchar(30) DEFAULT NULL,
  `NEW_STATUS` varchar(30) NOT NULL,
  `CHANGED_BY` bigint DEFAULT NULL,
  `NOTES` varchar(500) DEFAULT NULL,
  `CHANGED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ORDER_STATUS_HISTORY_ID`),
  KEY `FK_STATUS_HISTORY_USER` (`CHANGED_BY`),
  KEY `IDX_ORDER_STATUS_HISTORY_ORDER` (`ORDER_ID`),
  CONSTRAINT `FK_STATUS_HISTORY_ORDER` FOREIGN KEY (`ORDER_ID`) REFERENCES `orders` (`ORDER_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_STATUS_HISTORY_USER` FOREIGN KEY (`CHANGED_BY`) REFERENCES `users` (`USER_ID`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `orders`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `orders` (
  `ORDER_ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint NOT NULL,
  `SHIPPING_ADDRESS_ID` bigint DEFAULT NULL,
  `BILLING_ADDRESS_ID` bigint DEFAULT NULL,
  `COUPON_ID` bigint DEFAULT NULL,
  `ORDER_STATUS` varchar(30) NOT NULL DEFAULT 'PLACED',
  `SUBTOTAL_AMOUNT` decimal(12,2) NOT NULL,
  `DISCOUNT_AMOUNT` decimal(12,2) NOT NULL DEFAULT '0.00',
  `TAX_AMOUNT` decimal(12,2) NOT NULL DEFAULT '0.00',
  `SHIPPING_AMOUNT` decimal(12,2) NOT NULL DEFAULT '0.00',
  `TOTAL_AMOUNT` decimal(12,2) NOT NULL,
  `SHIPPING_NAME` varchar(255) NOT NULL,
  `SHIPPING_PHONE` varchar(20) DEFAULT NULL,
  `SHIPPING_ADDRESS_LINE_1` varchar(255) NOT NULL,
  `SHIPPING_ADDRESS_LINE_2` varchar(255) DEFAULT NULL,
  `SHIPPING_CITY` varchar(100) NOT NULL,
  `SHIPPING_STATE` varchar(100) NOT NULL,
  `SHIPPING_PINCODE` varchar(20) NOT NULL,
  `SHIPPING_COUNTRY` varchar(100) NOT NULL,
  `PURCHASED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DELIVERED_AT` datetime DEFAULT NULL,
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ORDER_ID`),
  KEY `FK_ORDER_SHIPPING_ADDRESS` (`SHIPPING_ADDRESS_ID`),
  KEY `FK_ORDER_BILLING_ADDRESS` (`BILLING_ADDRESS_ID`),
  KEY `FK_ORDER_COUPON` (`COUPON_ID`),
  KEY `IDX_ORDERS_USER` (`USER_ID`),
  KEY `IDX_ORDERS_STATUS` (`ORDER_STATUS`),
  KEY `IDX_ORDERS_PURCHASED_AT` (`PURCHASED_AT`),
  CONSTRAINT `FK_ORDER_BILLING_ADDRESS` FOREIGN KEY (`BILLING_ADDRESS_ID`) REFERENCES `addresses` (`ADDRESS_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_ORDER_COUPON` FOREIGN KEY (`COUPON_ID`) REFERENCES `coupons` (`COUPON_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_ORDER_SHIPPING_ADDRESS` FOREIGN KEY (`SHIPPING_ADDRESS_ID`) REFERENCES `addresses` (`ADDRESS_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_ORDER_USER` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`),
  CONSTRAINT `CHK_ORDER_AMOUNTS` CHECK (((`SUBTOTAL_AMOUNT` >= 0) and (`DISCOUNT_AMOUNT` >= 0) and (`TAX_AMOUNT` >= 0) and (`SHIPPING_AMOUNT` >= 0) and (`TOTAL_AMOUNT` >= 0))),
  CONSTRAINT `CHK_ORDER_STATUS` CHECK ((`ORDER_STATUS` in (_utf8mb4'PLACED',_utf8mb4'CONFIRMED',_utf8mb4'PROCESSING',_utf8mb4'SHIPPED',_utf8mb4'DELIVERED',_utf8mb4'CANCELLED',_utf8mb4'RETURNED')))
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `password_reset_tokens`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `password_reset_tokens` (
  `PASSWORD_RESET_TOKEN_ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint NOT NULL,
  `TOKEN_HASH` varchar(255) NOT NULL,
  `EXPIRES_AT` datetime NOT NULL,
  `USED_AT` datetime DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PASSWORD_RESET_TOKEN_ID`),
  UNIQUE KEY `UQ_PASSWORD_RESET_TOKEN` (`TOKEN_HASH`),
  KEY `FK_PASSWORD_RESET_USER` (`USER_ID`),
  CONSTRAINT `FK_PASSWORD_RESET_USER` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `payments`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `payments` (
  `PAYMENT_ID` bigint NOT NULL AUTO_INCREMENT,
  `ORDER_ID` bigint NOT NULL,
  `AMOUNT` decimal(12,2) NOT NULL,
  `PAYMENT_METHOD` varchar(50) NOT NULL,
  `PAYMENT_STATUS` varchar(30) NOT NULL DEFAULT 'PENDING',
  `PAYMENT_PROVIDER` varchar(100) DEFAULT NULL,
  `PROVIDER_REFERENCE` varchar(255) DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PAID_AT` datetime DEFAULT NULL,
  PRIMARY KEY (`PAYMENT_ID`),
  KEY `IDX_PAYMENTS_ORDER` (`ORDER_ID`),
  KEY `IDX_PAYMENTS_PROVIDER_REFERENCE` (`PROVIDER_REFERENCE`),
  CONSTRAINT `FK_PAYMENT_ORDER` FOREIGN KEY (`ORDER_ID`) REFERENCES `orders` (`ORDER_ID`),
  CONSTRAINT `CHK_PAYMENT_AMOUNT` CHECK ((`AMOUNT` > 0)),
  CONSTRAINT `CHK_PAYMENT_STATUS` CHECK ((`PAYMENT_STATUS` in (_utf8mb4'PENDING',_utf8mb4'AUTHORIZED',_utf8mb4'PAID',_utf8mb4'FAILED',_utf8mb4'CANCELLED',_utf8mb4'PARTIALLY_REFUNDED',_utf8mb4'REFUNDED')))
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `permissions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `permissions` (
  `PERMISSION_ID` bigint NOT NULL AUTO_INCREMENT,
  `PERMISSION_NAME` varchar(100) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`PERMISSION_ID`),
  UNIQUE KEY `UQ_PERMISSION_NAME` (`PERMISSION_NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `product_attributes`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `product_attributes` (
  `ATTRIBUTE_ID` bigint NOT NULL AUTO_INCREMENT,
  `PRODUCT_ID` bigint NOT NULL,
  `VARIANT_ID` bigint DEFAULT NULL,
  `ATTRIBUTE_NAME` varchar(100) NOT NULL,
  `ATTRIBUTE_VALUE` varchar(255) NOT NULL,
  PRIMARY KEY (`ATTRIBUTE_ID`),
  UNIQUE KEY `UQ_PRODUCT_ATTRIBUTE` (`PRODUCT_ID`,`VARIANT_ID`,`ATTRIBUTE_NAME`,`ATTRIBUTE_VALUE`),
  KEY `IDX_PRODUCT_ATTRIBUTES_PRODUCT` (`PRODUCT_ID`),
  KEY `IDX_PRODUCT_ATTRIBUTES_VARIANT` (`VARIANT_ID`),
  CONSTRAINT `FK_ATTRIBUTE_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `products` (`PRODUCT_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_ATTRIBUTE_VARIANT` FOREIGN KEY (`VARIANT_ID`) REFERENCES `product_variants` (`VARIANT_ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=80 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `product_categories`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `product_categories` (
  `PRODUCT_ID` bigint NOT NULL,
  `CATEGORY_ID` bigint NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`,`CATEGORY_ID`),
  KEY `IDX_PRODUCT_CATEGORIES_CATEGORY` (`CATEGORY_ID`),
  CONSTRAINT `FK_PRODUCT_CATEGORY_CATEGORY` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `categories` (`CATEGORY_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_PRODUCT_CATEGORY_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `products` (`PRODUCT_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `product_images`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `product_images` (
  `IMAGE_ID` bigint NOT NULL AUTO_INCREMENT,
  `PRODUCT_ID` bigint NOT NULL,
  `IMAGE_URL` varchar(2048) NOT NULL,
  `ALT_TEXT` varchar(255) DEFAULT NULL,
  `DISPLAY_ORDER` int NOT NULL DEFAULT '0',
  `IS_PRIMARY` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`IMAGE_ID`),
  KEY `IDX_PRODUCT_IMAGES_PRODUCT` (`PRODUCT_ID`),
  CONSTRAINT `FK_PRODUCT_IMAGE_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `products` (`PRODUCT_ID`) ON DELETE CASCADE,
  CONSTRAINT `CHK_IMAGE_DISPLAY_ORDER` CHECK ((`DISPLAY_ORDER` >= 0))
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `product_variants`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `product_variants` (
  `VARIANT_ID` bigint NOT NULL AUTO_INCREMENT,
  `PRODUCT_ID` bigint NOT NULL,
  `SKU` varchar(100) NOT NULL,
  `VARIANT_NAME` varchar(255) DEFAULT NULL,
  `VARIANT_DESCRIPTION` text,
  `PRICE` decimal(12,2) NOT NULL,
  `QUANTITY_AVAILABLE` int NOT NULL DEFAULT '0',
  `LOW_STOCK_THRESHOLD` int NOT NULL DEFAULT '5',
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`VARIANT_ID`),
  UNIQUE KEY `UQ_VARIANT_SKU` (`SKU`),
  KEY `IDX_PRODUCT_VARIANTS_PRODUCT` (`PRODUCT_ID`),
  CONSTRAINT `FK_VARIANT_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `products` (`PRODUCT_ID`) ON DELETE CASCADE,
  CONSTRAINT `CHK_LOW_STOCK_THRESHOLD` CHECK ((`LOW_STOCK_THRESHOLD` >= 0)),
  CONSTRAINT `CHK_VARIANT_PRICE` CHECK ((`PRICE` >= 0)),
  CONSTRAINT `CHK_VARIANT_QUANTITY` CHECK ((`QUANTITY_AVAILABLE` >= 0))
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `products`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `products` (
  `PRODUCT_ID` bigint NOT NULL AUTO_INCREMENT,
  `TAX_RATE_ID` bigint DEFAULT NULL,
  `PRODUCT_NAME` varchar(255) NOT NULL,
  `PRODUCT_DESCRIPTION` text,
  `BRAND` varchar(150) DEFAULT NULL,
  `BASE_PRICE` decimal(12,2) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`PRODUCT_ID`),
  KEY `FK_PRODUCT_TAX_RATE` (`TAX_RATE_ID`),
  KEY `IDX_PRODUCTS_NAME` (`PRODUCT_NAME`),
  KEY `IDX_PRODUCTS_BRAND` (`BRAND`),
  CONSTRAINT `FK_PRODUCT_TAX_RATE` FOREIGN KEY (`TAX_RATE_ID`) REFERENCES `tax_rates` (`TAX_RATE_ID`) ON DELETE SET NULL,
  CONSTRAINT `CHK_PRODUCT_PRICE` CHECK ((`BASE_PRICE` >= 0))
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `refresh_tokens`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `refresh_tokens` (
  `REFRESH_TOKEN_ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint NOT NULL,
  `TOKEN_HASH` varchar(255) NOT NULL,
  `EXPIRES_AT` datetime NOT NULL,
  `REVOKED_AT` datetime DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY_IP` varchar(45) DEFAULT NULL,
  `REPLACED_BY_TOKEN_HASH` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`REFRESH_TOKEN_ID`),
  UNIQUE KEY `UQ_REFRESH_TOKEN_HASH` (`TOKEN_HASH`),
  KEY `IDX_REFRESH_TOKEN_USER` (`USER_ID`),
  KEY `IDX_REFRESH_TOKEN_EXPIRY` (`EXPIRES_AT`),
  CONSTRAINT `FK_REFRESH_TOKEN_USER` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=205 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `refunds`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `refunds` (
  `REFUND_ID` bigint NOT NULL AUTO_INCREMENT,
  `PAYMENT_ID` bigint NOT NULL,
  `RETURN_ID` bigint DEFAULT NULL,
  `REFUND_AMOUNT` decimal(12,2) NOT NULL,
  `REFUND_STATUS` varchar(30) NOT NULL DEFAULT 'PENDING',
  `PROVIDER_REFERENCE` varchar(255) DEFAULT NULL,
  `REASON` varchar(255) DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PROCESSED_AT` datetime DEFAULT NULL,
  PRIMARY KEY (`REFUND_ID`),
  KEY `FK_REFUND_RETURN` (`RETURN_ID`),
  KEY `IDX_REFUNDS_PAYMENT` (`PAYMENT_ID`),
  CONSTRAINT `FK_REFUND_PAYMENT` FOREIGN KEY (`PAYMENT_ID`) REFERENCES `payments` (`PAYMENT_ID`),
  CONSTRAINT `FK_REFUND_RETURN` FOREIGN KEY (`RETURN_ID`) REFERENCES `returns` (`RETURN_ID`) ON DELETE SET NULL,
  CONSTRAINT `CHK_REFUND_AMOUNT` CHECK ((`REFUND_AMOUNT` > 0)),
  CONSTRAINT `CHK_REFUND_STATUS` CHECK ((`REFUND_STATUS` in (_utf8mb4'PENDING',_utf8mb4'PROCESSING',_utf8mb4'COMPLETED',_utf8mb4'FAILED',_utf8mb4'CANCELLED')))
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `return_items`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `return_items` (
  `RETURN_ITEM_ID` bigint NOT NULL AUTO_INCREMENT,
  `RETURN_ID` bigint NOT NULL,
  `ORDER_ITEM_ID` bigint NOT NULL,
  `QUANTITY` int NOT NULL,
  `ITEM_CONDITION` varchar(50) DEFAULT NULL,
  `RETURN_REASON` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`RETURN_ITEM_ID`),
  UNIQUE KEY `UQ_RETURN_ORDER_ITEM` (`RETURN_ID`,`ORDER_ITEM_ID`),
  KEY `FK_RETURN_ITEM_ORDER_ITEM` (`ORDER_ITEM_ID`),
  CONSTRAINT `FK_RETURN_ITEM_ORDER_ITEM` FOREIGN KEY (`ORDER_ITEM_ID`) REFERENCES `order_items` (`ORDER_ITEM_ID`),
  CONSTRAINT `FK_RETURN_ITEM_RETURN` FOREIGN KEY (`RETURN_ID`) REFERENCES `returns` (`RETURN_ID`) ON DELETE CASCADE,
  CONSTRAINT `CHK_RETURN_ITEM_QUANTITY` CHECK ((`QUANTITY` > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `returns`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `returns` (
  `RETURN_ID` bigint NOT NULL AUTO_INCREMENT,
  `ORDER_ID` bigint NOT NULL,
  `USER_ID` bigint NOT NULL,
  `RETURN_STATUS` varchar(30) NOT NULL DEFAULT 'REQUESTED',
  `RETURN_REASON` varchar(255) NOT NULL,
  `CUSTOMER_COMMENTS` text,
  `ADMIN_COMMENTS` text,
  `REQUESTED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `APPROVED_AT` datetime DEFAULT NULL,
  `RECEIVED_AT` datetime DEFAULT NULL,
  `COMPLETED_AT` datetime DEFAULT NULL,
  PRIMARY KEY (`RETURN_ID`),
  KEY `IDX_RETURNS_ORDER` (`ORDER_ID`),
  KEY `IDX_RETURNS_USER` (`USER_ID`),
  CONSTRAINT `FK_RETURN_ORDER` FOREIGN KEY (`ORDER_ID`) REFERENCES `orders` (`ORDER_ID`),
  CONSTRAINT `FK_RETURN_USER` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`),
  CONSTRAINT `CHK_RETURN_STATUS` CHECK ((`RETURN_STATUS` in (_utf8mb4'REQUESTED',_utf8mb4'APPROVED',_utf8mb4'REJECTED',_utf8mb4'PICKED_UP',_utf8mb4'RECEIVED',_utf8mb4'COMPLETED',_utf8mb4'CANCELLED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `reviews`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `reviews` (
  `REVIEW_ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint NOT NULL,
  `PRODUCT_ID` bigint NOT NULL,
  `ORDER_ITEM_ID` bigint DEFAULT NULL,
  `RATING` int NOT NULL,
  `REVIEW_TEXT` text,
  `REVIEW_STATUS` varchar(20) NOT NULL DEFAULT 'PENDING',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`REVIEW_ID`),
  UNIQUE KEY `UQ_USER_PRODUCT_REVIEW` (`USER_ID`,`PRODUCT_ID`),
  KEY `FK_REVIEW_ORDER_ITEM` (`ORDER_ITEM_ID`),
  KEY `IDX_REVIEWS_PRODUCT_STATUS` (`PRODUCT_ID`,`REVIEW_STATUS`),
  CONSTRAINT `FK_REVIEW_ORDER_ITEM` FOREIGN KEY (`ORDER_ITEM_ID`) REFERENCES `order_items` (`ORDER_ITEM_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_REVIEW_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `products` (`PRODUCT_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_REVIEW_USER` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`) ON DELETE CASCADE,
  CONSTRAINT `CHK_REVIEW_RATING` CHECK ((`RATING` between 1 and 5)),
  CONSTRAINT `CHK_REVIEW_STATUS` CHECK ((`REVIEW_STATUS` in (_utf8mb4'PUBLISHED',_utf8mb4'PENDING',_utf8mb4'APPROVED',_utf8mb4'REJECTED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `role_permissions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `role_permissions` (
  `ROLE_ID` bigint NOT NULL,
  `PERMISSION_ID` bigint NOT NULL,
  PRIMARY KEY (`ROLE_ID`,`PERMISSION_ID`),
  KEY `FK_ROLE_PERMISSION_PERMISSION` (`PERMISSION_ID`),
  CONSTRAINT `FK_ROLE_PERMISSION_PERMISSION` FOREIGN KEY (`PERMISSION_ID`) REFERENCES `permissions` (`PERMISSION_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_ROLE_PERMISSION_ROLE` FOREIGN KEY (`ROLE_ID`) REFERENCES `roles` (`ROLE_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `roles`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `roles` (
  `ROLE_ID` bigint NOT NULL AUTO_INCREMENT,
  `ROLE_NAME` varchar(50) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ROLE_ID`),
  UNIQUE KEY `UQ_ROLE_NAME` (`ROLE_NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `shipments`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `shipments` (
  `SHIPMENT_ID` bigint NOT NULL AUTO_INCREMENT,
  `ORDER_ID` bigint NOT NULL,
  `SHIPPING_PROVIDER` varchar(100) DEFAULT NULL,
  `TRACKING_NUMBER` varchar(255) DEFAULT NULL,
  `SHIPMENT_STATUS` varchar(30) NOT NULL DEFAULT 'PENDING',
  `SHIPPED_AT` datetime DEFAULT NULL,
  `EXPECTED_DELIVERY_AT` datetime DEFAULT NULL,
  `DELIVERED_AT` datetime DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`SHIPMENT_ID`),
  KEY `IDX_SHIPMENTS_ORDER` (`ORDER_ID`),
  KEY `IDX_SHIPMENTS_TRACKING` (`TRACKING_NUMBER`),
  CONSTRAINT `FK_SHIPMENT_ORDER` FOREIGN KEY (`ORDER_ID`) REFERENCES `orders` (`ORDER_ID`),
  CONSTRAINT `CHK_SHIPMENT_STATUS` CHECK ((`SHIPMENT_STATUS` in (_utf8mb4'PENDING',_utf8mb4'PACKED',_utf8mb4'SHIPPED',_utf8mb4'IN_TRANSIT',_utf8mb4'OUT_FOR_DELIVERY',_utf8mb4'DELIVERED',_utf8mb4'FAILED',_utf8mb4'RETURNED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tax_rates`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tax_rates` (
  `TAX_RATE_ID` bigint NOT NULL AUTO_INCREMENT,
  `TAX_NAME` varchar(100) NOT NULL,
  `COUNTRY` varchar(100) DEFAULT NULL,
  `STATE` varchar(100) DEFAULT NULL,
  `RATE_PERCENT` decimal(7,4) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `VALID_FROM` datetime DEFAULT NULL,
  `VALID_TO` datetime DEFAULT NULL,
  PRIMARY KEY (`TAX_RATE_ID`),
  CONSTRAINT `CHK_TAX_RATE` CHECK ((`RATE_PERCENT` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `user_roles`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `user_roles` (
  `USER_ID` bigint NOT NULL,
  `ROLE_ID` bigint NOT NULL,
  `ASSIGNED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`USER_ID`,`ROLE_ID`),
  KEY `FK_USER_ROLE_ROLE` (`ROLE_ID`),
  CONSTRAINT `FK_USER_ROLE_ROLE` FOREIGN KEY (`ROLE_ID`) REFERENCES `roles` (`ROLE_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_USER_ROLE_USER` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `users`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `users` (
  `USER_ID` bigint NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(255) NOT NULL,
  `PASSWORD_HASH` varchar(255) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `PHONE_NUMBER` varchar(20) DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `EMAIL_VERIFIED` tinyint(1) NOT NULL DEFAULT '0',
  `ACCOUNT_LOCKED` tinyint(1) NOT NULL DEFAULT '0',
  `FAILED_LOGIN_ATTEMPTS` int NOT NULL DEFAULT '0',
  `LOCKED_UNTIL` datetime DEFAULT NULL,
  `PASSWORD_CHANGED_AT` datetime DEFAULT NULL,
  `LAST_LOGIN_AT` datetime DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `UQ_USERS_EMAIL` (`EMAIL`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `wishlist_items`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `wishlist_items` (
  `WISHLIST_ITEM_ID` bigint NOT NULL AUTO_INCREMENT,
  `WISHLIST_ID` bigint NOT NULL,
  `PRODUCT_ID` bigint NOT NULL,
  `ADDED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`WISHLIST_ITEM_ID`),
  UNIQUE KEY `UQ_WISHLIST_PRODUCT` (`WISHLIST_ID`,`PRODUCT_ID`),
  KEY `FK_WISHLIST_ITEM_PRODUCT` (`PRODUCT_ID`),
  CONSTRAINT `FK_WISHLIST_ITEM_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `products` (`PRODUCT_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_WISHLIST_ITEM_WISHLIST` FOREIGN KEY (`WISHLIST_ID`) REFERENCES `wishlists` (`WISHLIST_ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `wishlists`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `wishlists` (
  `WISHLIST_ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint NOT NULL,
  `WISHLIST_NAME` varchar(100) NOT NULL DEFAULT 'DEFAULT',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`WISHLIST_ID`),
  UNIQUE KEY `UQ_USER_WISHLIST` (`USER_ID`,`WISHLIST_NAME`),
  CONSTRAINT `FK_WISHLIST_USER` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

