package com.sunglassstore.concurrency;

import com.sunglassstore.dto.request.AutomaticOfferRequest;
import com.sunglassstore.dto.response.AutomaticOfferResponse;
import com.sunglassstore.repository.AutomaticOfferRepository;
import com.sunglassstore.service.AutomaticOfferService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.concurrent.Callable;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Administrator concurrency on the automatic offer, against the real database engine.
 *
 * On the "mysql" profile, not H2, because both properties under test are database properties:
 *
 *   1. Only one offer can be active. The guarantee is a UNIQUE index on a generated column
 *      (ACTIVE_SINGLETON), which H2's schema — generated by Hibernate from the entity, where that
 *      column is deliberately unmapped — does not have at all. A green H2 run would prove nothing.
 *   2. A stale edit is refused rather than applied. The application check and the row lock both
 *      have to hold under genuine parallelism, not just in sequence.
 *
 * The E2E suite covers the sequential versions of both through real HTTP. What it cannot construct
 * is two administrators committing at the same instant, which is what this file is for.
 *
 * Opt-in via -Dconcurrency.tests=true, matching CheckoutConcurrencyIntegrationTest.
 */
@SpringBootTest
@ActiveProfiles("mysql")
@EnabledIfSystemProperty(named = "concurrency.tests", matches = "true")
class AutomaticOfferConcurrencyIntegrationTest {

    @Autowired private AutomaticOfferService offerService;
    @Autowired private AutomaticOfferRepository offerRepository;

    @BeforeEach
    void clearActiveOffers() {
        // Any offer left live by another test would make every activation below fail for the wrong
        // reason. Archived rather than deleted, because ORDERS may reference them.
        offerRepository.findAll().forEach(offer -> {
            if (Boolean.TRUE.equals(offer.getIsActive()) || offer.getArchivedAt() == null) {
                offer.setIsActive(false);
                offer.setArchivedAt(LocalDateTime.now());
                offerRepository.save(offer);
            }
        });
    }

    private AutomaticOfferRequest request(String name, BigDecimal discountPerGroup, Long version) {
        AutomaticOfferRequest request = new AutomaticOfferRequest();
        request.setOfferName(name);
        request.setRequiredQuantity(2);
        request.setDiscountPerGroup(discountPerGroup);
        request.setMinimumOrderSubtotal(BigDecimal.ZERO);
        request.setScopeType("ALL_PRODUCTS");
        request.setProductIds(Set.of());
        request.setCategoryIds(Set.of());
        request.setStartsAt(LocalDateTime.now().minusHours(1));
        request.setEndsAt(LocalDateTime.now().plusDays(30));
        request.setIsActive(false);
        request.setPriority(0);
        request.setVersion(version);
        return request;
    }

    /** Runs every task at once and reports how many succeeded, so a race cannot be missed by timing. */
    private <T> Outcome runTogether(List<Callable<T>> tasks) throws Exception {
        ExecutorService pool = Executors.newFixedThreadPool(tasks.size());
        CountDownLatch start = new CountDownLatch(1);
        List<Future<T>> futures = new ArrayList<>();
        try {
            for (Callable<T> task : tasks) {
                futures.add(pool.submit(() -> {
                    start.await();
                    return task.call();
                }));
            }
            start.countDown();
            AtomicInteger succeeded = new AtomicInteger();
            AtomicInteger failed = new AtomicInteger();
            List<String> failures = new ArrayList<>();
            for (Future<T> future : futures) {
                try {
                    future.get(30, TimeUnit.SECONDS);
                    succeeded.incrementAndGet();
                } catch (Exception rejected) {
                    failed.incrementAndGet();
                    Throwable cause = rejected.getCause() == null ? rejected : rejected.getCause();
                    failures.add(cause.getClass().getSimpleName() + ": " + cause.getMessage());
                }
            }
            return new Outcome(succeeded.get(), failed.get(), failures);
        } finally {
            pool.shutdownNow();
        }
    }

    private record Outcome(int succeeded, int failed, List<String> failures) {}

    @Test
    @DisplayName("four administrators activating four offers at once leave exactly one live")
    void onlyOneOfferSurvivesSimultaneousActivation() throws Exception {
        List<AutomaticOfferResponse> drafts = new ArrayList<>();
        for (int index = 0; index < 4; index++) {
            drafts.add(offerService.create(
                    request("Concurrency draft " + index, new BigDecimal("500.00"), null), null));
        }

        List<Callable<AutomaticOfferResponse>> activations = new ArrayList<>();
        for (AutomaticOfferResponse draft : drafts) {
            activations.add(() -> offerService.setActive(
                    draft.automaticOfferId(), true, draft.version(), null));
        }

        Outcome outcome = runTogether(activations);

        long live = offerRepository.findAll().stream()
                .filter(offer -> Boolean.TRUE.equals(offer.getIsActive()) && offer.getArchivedAt() == null)
                .count();
        assertEquals(1, live, "exactly one offer may be live: " + outcome.failures());
        assertEquals(1, outcome.succeeded(), "exactly one activation may report success");
        assertEquals(3, outcome.failed(), "the other three must be refused, not silently ignored");
        // And refused for the right reason, rather than by some unrelated error.
        assertTrue(outcome.failures().stream().allMatch(message ->
                        message.toLowerCase().contains("already the active")
                                || message.toLowerCase().contains("constraint")
                                || message.toLowerCase().contains("duplicate")),
                "each refusal should name the conflict: " + outcome.failures());
    }

    @Test
    @DisplayName("simultaneous edits from the same version: one wins, the rest are refused")
    void concurrentEditsDoNotOverwriteEachOther() throws Exception {
        AutomaticOfferResponse offer = offerService.create(
                request("Concurrency edit target", new BigDecimal("500.00"), null), null);
        Long sharedVersion = offer.version();

        List<Callable<AutomaticOfferResponse>> edits = new ArrayList<>();
        for (int index = 1; index <= 4; index++) {
            BigDecimal amount = new BigDecimal(600 + index * 100).setScale(2);
            edits.add(() -> offerService.update(offer.automaticOfferId(),
                    request("Concurrency edit target", amount, sharedVersion), null));
        }

        Outcome outcome = runTogether(edits);

        assertEquals(1, outcome.succeeded(),
                "only the administrator who held the current version may write: " + outcome.failures());
        assertEquals(3, outcome.failed());
        assertTrue(outcome.failures().stream().allMatch(message ->
                        message.toLowerCase().contains("updated elsewhere")),
                "a stale edit must be a conflict, not a lost update: " + outcome.failures());

        // The surviving value is one of the four proposed amounts — never a blend of them.
        BigDecimal stored = offerRepository.findById(offer.automaticOfferId()).orElseThrow()
                .getDiscountPerGroup();
        assertTrue(List.of(new BigDecimal("700.00"), new BigDecimal("800.00"),
                        new BigDecimal("900.00"), new BigDecimal("1000.00")).contains(stored),
                "stored amount should be exactly one administrator's value, was " + stored);
        assertEquals(sharedVersion + 1, offerRepository.findById(offer.automaticOfferId()).orElseThrow().getVersion(),
                "exactly one version increment, i.e. exactly one write");
    }
}
